output "db_endpoint" {
  value = aws_db_instance.postgres.endpoint
}

output "db_name" {
  value = aws_db_instance.postgres.db_name
}

output "db_user" {
  value = aws_db_instance.postgres.username
}

// for debugging reasons, we output the autogenerated password
// this is usually discouraged in production environments, but for our usecase it is fine.
output "db_password" {
  value     = random_password.db_password.result
  sensitive = true
}

output "eks_cluster_name" {
  value = module.eks.cluster_name
}

output "ecr_repository_url" {
  value = aws_ecr_repository.app_repo.repository_url
}

output "grafana_url" {
  # changed from kubernetes_service_v1 to kubernetes_ingress_v1
  value       = try("http://${data.kubernetes_ingress_v1.grafana.status[0].load_balancer[0].ingress[0].hostname}", "Unavailable during teardown")
  description = "Grafana public URL"
}

output "grafana_password" {
  value       = random_password.grafana_password.result
  description = "Grafana admin password"
  sensitive   = true
}

output "argocd_password" {
  # Terraform automatically base64-decodes the secret data for you
  # yes not secure to output the password, but for our usecase it simplifies the process of logging into ArgoCD
  value       = try(data.kubernetes_secret_v1.argocd_password.data["password"], "Unavailable during teardown")
  description = "ArgoCD initial admin password"
  sensitive   = true
}

output "argocd_url" {
  value       = "http://${data.kubernetes_ingress_v1.argocd_url_fetcher.status[0].load_balancer[0].ingress[0].hostname}"
  description = "ArgoCD public URL"
}